### ISSUE TITLE
[CI] Implement golangci-lint

### ISSUE THREAD

**Issue by KEINOS** [KEINOS/go-sortfile#1]
Example of `.golangci.yml`

```yaml
run:
  tests: true
  fast: true
  build-tags:
    - golangci
  skip-dirs:
    - .github
    - .vscode
  allow-parallel-runners: true

output:
  format: colored-line-number
  sort-results: true

linters:
  enable-all: true
  disable:
  # Disable deprecated/abandoned linters
  - golint
  - interfacer
  - ifshort
  - scopelint
  - exhaustivestruct
  - maligned
  - nosnakecase
  - varcheck
  - deadcode
  # Disabled because of generics
  - contextcheck
  - rowserrcheck
  - sqlclosecheck
  - structcheck
  - wastedassign
  # Disable due to mock private functions
  - testpackage
```
